$script = <<-SCRIPT                                                            
sudo sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
sudo service ssh restart
sudo useradd -m -d /home/moon -s /bin/bash moon 
sudo echo "moon:welcome1" | sudo chpasswd 
sudo mkdir -p /home/moon/.ssh
sudo cp /tmp/authorized_keys /home/moon/.ssh/authorized_keys
sudo chown moon:moon /home/moon/.ssh/authorized_keys
sudo su -
echo -e "moon\tALL=(ALL)\tNOPASSWD: ALL"> /etc/sudoers.d/moon
exit
SCRIPT

Vagrant.configure(2) do |config|
        #Basic Configuration
        config.vm.box = "ubuntu/bionic64"
	config.vm.provision "file", source: "~/vagrant-project/id_rsa.pub", destination: "/tmp/authorized_keys"
	config.vm.provision "shell", inline: $script

        (1..2).each do |i|
                vmName = "ubuntu-client#{i}"
                vmIP = "10.0.0.3#{i}"
                config.vm.define vmName do |server|
                        server.vm.hostname = vmName
                        server.vm.network "public_network", ip: vmIP
                end
        end
end
